name: native_audio_controller
description: A Flutter plugin to handle pause/play for running music in background from another app
version: 0.0.1+1
homepage: https://github.com/tglRazaf/flutter-native-music-controller.git
repository: https://github.com/tglRazaf/flutter-native-music-controller.git

environment:
  sdk: '>=2.19.5 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.stephano.native_audio_controller
        pluginClass: NativeAudioControllerPlugin
      ios:
        pluginClass: NativeAudioControllerPlugin

platforms:
  android: